version: 2
updates:
  - package-ecosystem: npm
    directory: /design-system
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /social/linkedin
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /social/tiktok
    schedule:
      interval: weekly
